[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
pumpdotfun = "YOUR CONTRACT ADDRESS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/root/key.json"

[scripts]
client = "yarn run ts-node client/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
